name: Generate coverage

on:
  push:
    branches:
      - 'main'
      - 'hotfix/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.5"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Perform unit tests
        run: |
          coverage run --omit='./tests/*' \
          -m pytest -o log_cli=true -v
      - name: Generate coverage report
        run: coverage lcov
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
          git-branch: main
